export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <p className="bg:indigo-500">Header</p>
        </header>
        {children}
        <footer>
          <p class="bg:indigo-500">Footer</p>
        </footer>
      </body>
    </html>
  );
}
